### ISSUE TITLE
context_io.get_accounts() Exception: HTTP 105: Invalid signature

### ISSUE THREAD

**Issue by Aaln** [contextio/Python-ContextIO#25]
>>> context_io.get_accounts(email="aaron@thecompassmag.com")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/contextio-1.6-py2.7.egg/contextio/__init__.py", line 312, in get_accounts
    'accounts', params=params
  File "/usr/local/lib/python2.7/site-packages/contextio-1.6-py2.7.egg/contextio/__init__.py", line 226, in _request_uri
    self._handle_request_error(response)
  File "/usr/local/lib/python2.7/site-packages/contextio-1.6-py2.7.egg/contextio/__init__.py", line 267, in _handle_request_error
    response_json['value']
Exception: HTTP 105: Invalid signature SmRgFmL3r4uGE2ZSO/3Cz2/EAQE=. Signature base string should be GET&https%3A%2F%2Fapi.context.io%2F2.0%2Faccounts&email%3D[EMAIL]%26oauth_consumer_key%[CONSUMER_KEY]%26oauth_nonce%3D392bf108a9749bf82973849263fa67adf70f9a37%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1438543737%26oauth_version%3D1.0

**Comment by sushithegreat** [comment]
For dev-specific issues like this, send us a [support request](http://support.context.io/hc/en-us/requests/new). Thanks!
