### ISSUE TITLE
'include_body' and 'include_source' are not working

### ISSUE THREAD

**Issue by mou55** [contextio/Python-ContextIO#36]
I have to use get_body() (make an additional API call) in order to get a message body, because using 'include_body' or  'include_source' params doesn't retrieve the message body (or raw source)

**Comment by mou55** [comment]
and sometimes I get this error when calling  get_body()
```
>>> message.get()
True
>>> message.get_body()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/src/contextio-master/contextio/__init__.py", line 1975, in get_body
    self.body = self._request_uri('body', params=params)
  File "/src/contextio-master/contextio/__init__.py", line 616, in _request_uri
    uri, method=method, params=params, headers=headers, body=body
  File "/src/contextio-master/contextio/__init__.py", line 616, in _request_uri
    uri, method=method, params=params, headers=headers, body=body
  File "/src/contextio-master/contextio/__init__.py", line 227, in _request_uri
    self._handle_request_error(response)
  File "/src/contextio-master/contextio/__init__.py", line 278, in _handle_request_error
    raise Exception(response.text)
Exception: -1
```

**Comment by elmkarami** [comment]
:+1:

**Comment by mou55** [comment]
nvm for the second point https://github.com/contextio/Python-ContextIO/issues/36#issuecomment-170880082, I think it happens when the account is DISABLED

**Comment by mou55** [comment]
actually it's not working only with this call
 message = c.Message(account, {'message_id': '568cf354bb697b5d198b456d', 'include_body': 1})
